import Layout from "@/components/Layout";
import ItemForm from "@/components/ItemForm";
import { getSession } from "next-auth/react";
import axios from "axios";
import { prisma } from '@/lib/prisma';
import nodemailer from 'nodemailer';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import { prisma } from '@/lib/prisma';
import Handlebars from 'handlebars';
import { readFileSync } from 'fs';
import path from 'path';